# -*- coding: utf-8 -*-
"""Gráficos

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1X0e4QvtwQh7wmM0zs6Ms--IMLGjVJrB3
"""

import numpy as np
import matplotlib.pyplot as plt

x=np.arange(0.0,2.0,0.01)
y=1+np.sin(2*np.pi*x)
y2=1+np.cos(2*np.pi*x)

fig,ax=plt.subplots()

ax.plot(x,y,'--',x,y2)

#print(x)
#print(y)

import numpy as np
import matplotlib.pyplot as plt

x=np.arange(0.0,4.0,0.01)
y=1/(1+np.exp(-x))

fig,ax=plt.subplots()

ax.plot(x,y)

import numpy as np
import matplotlib.pyplot as plt



fig,ax=plt.subplots()

ax.plot(x,y)

import numpy as np
import matplotlib.pyplot as plt

x=np.arange(0.0,4.0,0.01)
y=x**2-x-2


fig,ax=plt.subplots()

ax.plot(x,y)

import numpy as np
import matplotlib.pyplot as plt

x=np.arange(0.0,4.0,0.01)
y=(x+(np.sin(x)))**2/(np.cos(x))*np.pi*(np.cos(x))/(np.sin(x))

fig,ax=plt.subplots()
ax.plot(x,y)

import numpy as np
import matplotlib.pyplot as plt

x=np.arange(-10.0,10.0,0.001)
y=x**2

fig,ax=plt.subplots()

ax.plot(x,y)

import numpy as np
import matplotlib.pyplot as plt

x=np.arange(-10.0,10.0,0.001)
y=np.sin(x+(2*np.pi*x))

fig,ax=plt.subplots()

ax.plot(x,y)

import numpy as np
import matplotlib.pyplot as plt

x=np.arange(-10.0,10.0,0.001)
y=np.cos((np.pi/6)+(4*np.pi*x))

fig,ax=plt.subplots()

ax.plot(x,y)

import numpy as np
import matplotlib.pyplot as plt

x=np.arange(-10.0,10.0,0.001)
y=[]
for v in x:
  if v<=1:
    y.append(1-v)
  if v>1:
    y.append(v**2)

fig,ax=plt.subplots()

ax.plot(x,y)

import numpy as np
import matplotlib.pyplot as plt

x=np.arange(-10.0,10.0,0.001)
y=-(x-1)-(x+2)

fig,ax=plt.subplots()

ax.plot(x,y)

import numpy as np
import matplotlib.pyplot as plt

x=np.arange(-10.0,10.0,0.001)
y=-(x**3-(2.5*x))

fig,ax=plt.subplots()

ax.plot(x,y)

import numpy as np
import matplotlib.pyplot as plt

x=np.arange(-10.0,10.0,0.001)
y=[]
for v in x:
  if v<=-2:
    y.append(-2*v-1)
  if -2<v and v<1:
    y.append(3)
  if 1<v:
    y.append(2*v+1)
    

fig,ax=plt.subplots()
ax.plot(x,y)

import numpy as np
import matplotlib.pyplot as plt

x=np.arange(-10.0,10.0,0.001)
y=-((x**2)-(2*5*x))

fig,ax=plt.subplots()

ax.plot(x,y)

import numpy as np
import matplotlib.pyplot as plt

x=np.arange(-10.0,10.0,0.001)
y=(x**2-1)/(x-1)

fig,ax=plt.subplots()

ax.plot(x,y)

import numpy as np
import matplotlib.pyplot as plt

x=np.arange(-10.0,10.0,0.001)
y=x+(1/x)

fig,ax=plt.subplots()
ax.plot(x,y)